### ISSUE TITLE
Failed to load resource 404

### ISSUE THREAD

**Issue by lyquocnam** [reel/feathers-nextjs#5]
![image](https://cloud.githubusercontent.com/assets/8347826/21667357/e8b8c6a2-d32a-11e6-91a4-e4da32ffa0de.png)

**Comment by reel** [comment]
I tried to proxy the webpack hmr from feathers to webpack without success.

If you work on React, i'd suggest running `npm run both` and looking at `http://localhost:3000`

Possible cause is that we don't call `view.prepare()` before running the express server (https://github.com/zeit/next.js/blob/master/examples/custom-server-express/server.js#L8)

**Comment by reel** [comment]
From what I can see, it was only a syntax error on my side that I carried over:

https://github.com/reel/feathers-nextjs/blob/wrapping-app/src/app.js#L19

Should be:

`const view = next({ dir: '.', dev: true });`

instead of:

`const view = next('.', { dev: true });`

**Comment by lyquocnam** [comment]
this awesome and super fast ! thanks @reel !
